quarkus.application.name=store-service
quarkus.http.port=8082
#quarkus.datasource.db-kind=h2
quarkus.devservices.enabled=false

quarkus.package.jar.enabled=true
quarkus.package.jar.type=uber-jar
quarkus.package.runner-suffix=runner



quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
#
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
#

mp.messaging.incoming.consumer.connector=smallrye-kafka
mp.messaging.incoming.consumer.topic=NAME_TOPIC
mp.messaging.incoming.consumer.failure-strategy=dead-letter-queue
mp.messaging.incoming.consumer.dead-letter-queue.topic=NAME_TOPIC_ERROR
mp.messaging.incoming.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.consumer.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.consumer.group.id=${quarkus.application.name}
mp.messaging.incoming.consumer.auto.offset.reset=earliest

smallrye.messaging.observation.enabled=true

mp.messaging.incoming.consumer.tracing-enabled=true
mp.messaging.outgoing.producer.tracing-enabled=true
quarkus.datasource.jdbc.telemetry.trace-connection=true
quarkus.datasource.jdbc.telemetry=true
quarkus.messaging.metrics.enabled=true
quarkus.otel.instrument.jvm-metrics=true
quarkus.datasource.metrics.enabled=true
#quarkus.otel.simple=true
quarkus.micrometer.export.otlp.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.kafka.enabled=true
quarkus.micrometer.binder.enable-all=true
quarkus.micrometer.binder.system=true
quarkus.datasource.jdbc.metrics.enabled=true

quarkus.micrometer.binder-enabled-default=false
quarkus.otel.metrics.jvm.enabled=true
quarkus.micrometer.binder.http-server.enabled=true



mp.messaging.outgoing.producer.connector=smallrye-kafka
mp.messaging.outgoing.producer.topic=NAME_TOPIC
mp.messaging.outgoing.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.bootstrap.servers=localhost:9092

quarkus.shutdown.timeout=200

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.metrics.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.tracing.exporter=otlp