quarkus.devservices.enabled=false

quarkus.langchain4j.chat-model.provider=anthropicp
quarkus.langchain4j.custom.anthropicp.api-key=Bearer ${API_KEY}
quarkus.langchain4j.custom.anthropicp.base-url=${BASE_URL}
#quarkus.langchain4j.custom.anthropicp.chat-model.thinking.send-thinking=true
#quarkus.langchain4j.custom.anthropicp.chat-model.thinking.return-thinking=true
quarkus.langchain4j.custom.anthropicp.chat-model.model-name=claude-sonnet-4-6
quarkus.langchain4j.custom.anthropicp.chat-model.temperature=0.7
quarkus.langchain4j.custom.anthropicp.timeout=60000
quarkus.langchain4j.custom.anthropicp.chat-model.max-tokens=32892

quarkus.log.min-level=INFO
quarkus.log.category."io.quarkiverse.langchain4j.mcp.runtime.http".level=INFO

quarkus.langchain4j.mcp.test.transport-type=http
quarkus.langchain4j.mcp.test.url=${MCP_URL}

#quarkus.langchain4j.log-requests-curl=true
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

quarkus.mailer.host=localhost
quarkus.mailer.port=25
quarkus.mailer.from=${FROM}
quarkus.mailer.mock=false
quarkus.mailer.tls=false
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.trust-all=true